# Generated by Django 5.2.12 on 2026-09-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0086_spare_shop_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardspareitem',
            name='transport_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Transport paid to bring this part in — never owed to the shop (SHOP rows only)', max_digits=10, null=True),
        ),
    ]
