# Generated by Django 5.2.12 on 2026-10-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0087_jobcardspareitem_transport_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='kind',
            field=models.CharField(choices=[('JOB', 'Job'), ('WARRANTY', 'Warranty')], db_default='JOB', db_index=True, default='JOB', editable=False, help_text='JOB, or WARRANTY — free work because of an earlier bill', max_length=10),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='warranty_for',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text="WARRANTY cards only: the earlier bill's number (e.g. JB-26-007)", max_length=20, null=True),
        ),
    ]
