# Generated by Django 5.2.12 on 2026-10-07 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0088_jobcard_kind_warranty_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardspareitem',
            name='replaces',
            field=models.ForeignKey(blank=True, editable=False, help_text='Warranty: the earlier part this claimed part replaces', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='workshop.jobcardspareitem'),
        ),
        migrations.AddField(
            model_name='jobcardspareitem',
            name='replaces_line',
            field=models.ForeignKey(blank=True, editable=False, help_text='Warranty: the Excel-era old bill line this claimed part replaces', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='workshop.oldbillpartline'),
        ),
    ]
