# Generated by Django 5.2.12 on 2026-10-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0089_spare_replaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardspareitem',
            name='expected_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Days the shop expects the part to take, counted from the ordered date', null=True),
        ),
    ]
